// netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--build-from-source"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = true
  conditions = {Path = "/_next/static/**"}

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[functions]
  # Increase the timeout for functions that might take longer to build
  node_bundler = "esbuild"
  external_node_modules = ["secure-password"]

// package.json additions
{
  "dependencies": {
    "@netlify/plugin-nextjs": "latest",
    "secure-password": "4.0.0"
  },
  "scripts": {
    "postinstall": "npm rebuild secure-password --build-from-source",
    "build": "next build",
    "dev": "next dev"
  }
}

// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  target: 'serverless',
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.externals.push({
        'secure-password': 'commonjs secure-password'
      })
    }
    return config
  },
}

module.exports = nextConfig