[build]
  # Run clean install and generate Prisma client before build
  command = "npm ci && npx prisma generate && blitz build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"
  NEXT_USE_NETLIFY_EDGE = "true"
  # Force Prisma to generate fresh client
  PRISMA_GENERATE_DATAPROXY = "true"
  # Disable Netlify cache for node_modules to ensure fresh installs
  NETLIFY_USE_YARN_CACHE = "false"
  NETLIFY_USE_NPM_CACHE = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  conditions = {Path = {excluded_patterns = ["/_next/*", "/api/*", "/static/*"]}}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"