[build]
  # Add prisma generate before the build command
  command = "npx prisma generate && blitz build"
  functions = "netlify/functions"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"
  NEXT_USE_NETLIFY_EDGE = "true"
  # Force Prisma to generate fresh client
  PRISMA_GENERATE_DATAPROXY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Clear cache if Prisma schema changes
[[plugins]]
  package = "netlify-plugin-cache-bust"
    [plugins.inputs]
      # Bust cache when prisma schema changes
      sourceFile = "prisma/schema.prisma"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  conditions = {Path = {excluded_patterns = ["/_next/*", "/api/*", "/static/*"]}}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"